platform :ios, '10.3'


target 'iOSProject' do

inhibit_all_warnings!

# 网络请求
pod 'AFNetworking'
#pod 'ASIHTTPRequest'

# 网络监控
pod 'Reachability'

#字典转模型
pod 'MJExtension'
# 下拉刷新
pod 'MJRefresh'
# 图片加载
pod 'SDWebImage'
pod 'SDWebImage/GIF'

#用于适配
pod 'Masonry'

#友盟统计和分享
pod 'UMengAnalytics'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/Sina'

#百度地图SDK
pod 'BaiduMapKit', '4.1.1'

# 表情键盘
#pod 'HMEmoticon'
# 正则匹配点击
pod 'KILabel'

# YYKit
#pod 'YYKit'
pod 'YYImage'
pod 'YYText'
pod 'YYAsyncLayer'
pod 'YYCategories'

# 数据库
pod 'FMDB'

# 蒙版
pod 'MBProgressHUD'

# 进度
pod 'M13ProgressSuite'

# 无限轮播
pod 'SDCycleScrollView'

# 键盘管理
pod 'IQKeyboardManager'

# 唯一设备标识
pod 'FCUUID'


# 三级联动 时间 地址
pod 'MOFSPickerManager'

# 全局滑动
pod 'FDFullscreenPopGesture'

# toast
pod 'Toast'

# 二维码
pod 'HMQRCodeScanner'

# 照片
pod 'TZImagePickerController'

# scrollpageView
pod 'ZJScrollPageView'

# 列表视频
pod 'ZFPlayer', '2.1.6'
#pod 'ZFDownload'

# mark- 好玩的
# 泡泡uibutton
pod 'DWBubbleMenuButton'

# 动态 collectionView
#pod 'LxGridView'
# 指纹识别
#pod 'TDTouchID'
# h5交互
#pod 'WebViewJavascriptBridge'
# 脸部识别
#pod 'iflyMSC'
# 环信连天包含实时语音版本
# pod 'Hyphenate'
# pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

end
