platform :ios, '9.1'


target 'PLMMPRJK' do
    
    inhibit_all_warnings!

#网络请求
pod "AFNetworking"
pod 'ASIHTTPRequest'

#字典转模型
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
#用于适配
pod 'Masonry'
#友盟统计
pod 'UMengAnalytics'
#百度地图SDK
pod 'BaiduMapKit'

#包含实时语音版本 SDK（Hyphenate），引用时 #import <Hyphenate/Hyphenate.h>
#pod 'Hyphenate'


pod 'ActionSheetPicker-3.0'

pod 'CYLTabBarController'

# 正则匹配
pod 'RegexKitLite'

pod 'SVProgressHUD'

pod 'MWPhotoBrowser'

# 表情键盘
pod 'HMEmoticon'
pod 'KILabel'

# yykit
pod 'YYKit'


pod 'MagicWindowSDK'

# 数据库
pod 'FMDB'

pod 'ActionSheetPicker-3.0'


# 二维码
pod 'LBXScan'
pod 'HMQRCodeScanner'

# 蒙版
pod 'MBProgressHUD'
pod 'MWPhotoBrowser'
# h5交互
pod 'WebViewJavascriptBridge', '~> 5.0'

# 进度
pod 'M13ProgressSuite'

end
