platform :ios, '9.1'


target 'PLMMPRJK' do

#网络请求
pod "AFNetworking"

#字典转模型
pod 'MJExtension'

pod 'SDWebImage'


#用于适配
pod 'Masonry'
#友盟统计

pod 'BaiduMapKit' #百度地图SDK


pod 'UMengSocial'  #友盟社会化分享及第三方登录


pod 'ActionSheetPicker-3.0'


pod 'RegexKitLite'


pod 'MBProgressHUD'

pod 'MWPhotoBrowser'


pod 'YYKit'



end
