platform :ios, '8.1'


target 'PLMMPRJK' do

#网络请求
pod "AFNetworking"

#字典转模型
pod 'MJExtension'

pod 'SDWebImage'

pod 'JSONModel'

#用于适配
pod 'Masonry'
#友盟统计
pod 'UMengAnalytics'

pod 'FMDB/common'

pod 'FMDB/SQLCipher'

pod 'CocoaLumberjack'

pod 'BaiduMapKit' #百度地图SDK


pod 'GTSDK'  #个推SDK

pod 'UMengSocial'  #友盟社会化分享及第三方登录

pod 'FLEX', '~> 2.0', :configurations => ['Debug']

pod 'ActionSheetPicker-3.0'



pod 'XAspect'

pod 'CYLTabBarController'

pod 'LKDBHelper'

pod 'RegexKitLite'

pod 'IQKeyboardManager' #兼容IOS7

pod 'LBXScan'

pod 'MBProgressHUD'

pod 'MWPhotoBrowser'

pod 'M13ProgressSuite'

pod 'WebViewJavascriptBridge'

pod 'YYText'

#pod 'MLeaksFinder'
#可以把它放在MobileProject_Local的target中 这样就不会影响到产品环境



end
